  on: push
  permissions:
    packages: write
    contents: read

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Run the Maven verify phase
          working-directory: grafana-kotlin-dsl
          run: mvn --batch-mode --update-snapshots verify

        - name: Start integrations evnvironment
          working-directory: test-environment
          run: chmod 777 ./startup && ./startup.sh

        - name: Run integration tests
          working-directory: grafana-kotlin-dsl
          run: mvn failsafe:integration-test

        - name: Publish package
          working-directory: grafana-kotlin-dsl
          run: mvn --batch-mode deploy -DskipTests
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
